import { Link } from 'react-router-dom'
import LegalLayout from '../components/LegalLayout'

export default function PrivacyPolicy() {
  return (
    <LegalLayout
      eyebrow="LEGAL"
      title="Privacy Policy"
      updated="16 July 2026"
      intro="Houseker Estates (operating under the Houseker / Chinar Estates brand) helps Kashmiri property owners and overseas investors buy, verify, and manage estates remotely. This policy explains what information we collect through our app and website, why we collect it, and the choices you have."
    >
      <h2>1. Who this policy covers</h2>
      <p>
        This policy applies to anyone who visits this website, creates an account on the
        Houseker Estates mobile app, or submits a service request to our team — whether
        you're a landowner, buyer/investor, a Non-Resident Kashmiri (NRK), or a Kashmiri
        Pandit (KP) client using our KP-specific services.
      </p>

      <h2>2. Information we collect</h2>
      <h3>Account information</h3>
      <ul>
        <li>Name, phone number, email address, country of residence, and preferred language.</li>
        <li>A profile photo, if you choose to add one.</li>
        <li>Your user type (e.g. NRK, KP, landowner, buyer/investor) and KYC verification status.</li>
      </ul>
      <h3>Property &amp; service-request information</h3>
      <ul>
        <li>
          Property details you submit — address, district, tehsil/village, GPS coordinates,
          property type, area, and ownership status.
        </li>
        <li>
          Case- or enquiry-specific details for the service you request (for example, expected
          sale price for a Property Sale, or transfer details for Remittance &amp; Tax support).
        </li>
        <li>
          Documents you upload — identity documents, property papers, legal documents, and
          payment proofs — each tagged by category and access level.
        </li>
      </ul>
      <h3>Information generated during service delivery</h3>
      <ul>
        <li>
          On-ground field reports prepared by our inspection officers for services like
          Encroachment Check — including geotagged photos/videos of the property and an
          inspection assessment.
        </li>
        <li>
          Payment records (amount, currency, purpose, and status) for services you've been
          billed for. We do not store your card or bank account numbers on our platform.
        </li>
        <li>Notes and status updates our team logs against your case as it progresses.</li>
      </ul>
      <h3>Location data</h3>
      <p>
        If you grant permission, our app reads your device's GPS location to help auto-fill a
        property address using Google Maps. We only use this at the moment you request it —
        we do not continuously track your location in the background.
      </p>

      <h2>3. How we collect information</h2>
      <p>
        Most information is provided directly by you — through sign-up, service request forms,
        document uploads, or conversations with your account manager. Some information (like
        field inspection reports) is generated by our own staff while delivering a service you
        requested, and is attached to your case file.
      </p>

      <h2>4. How we use your information</h2>
      <ul>
        <li>To create and secure your account, and verify your identity via OTP.</li>
        <li>To deliver the services you request — legal verification, encroachment checks, power of attorney processing, ancestral property tracing, remittance and tax support, document procurement, and property management.</li>
        <li>To communicate with you about your case, service updates, and support requests.</li>
        <li>To coordinate with the certified legal experts, on-ground field officers, and financial advisors who work on your case.</li>
        <li>To maintain accurate financial and case records, including for tax and audit purposes.</li>
        <li>To improve our services and troubleshoot issues you report.</li>
      </ul>

      <h2>5. Who we share information with</h2>
      <p>We do not sell your personal information. We share it only:</p>
      <ul>
        <li>
          With the professionals actually working your case — our in-house legal team,
          empanelled field/inspection officers, and financial advisors — limited to what each
          needs to complete their part of the service.
        </li>
        <li>
          With the infrastructure providers that run our app and website:{' '}
          <strong>Firebase (Google)</strong> for phone/Google sign-in authentication,{' '}
          <strong>Cloudinary</strong> for secure storage of profile images and uploaded
          documents, and <strong>Google Maps Platform</strong> for address lookup and
          geocoding. These providers process data on our behalf under their own security and
          data-processing terms.
        </li>
        <li>
          With government authorities, courts, or land-records offices where this is a
          necessary part of the service you requested (for example, filing a Power of Attorney
          or verifying a title).
        </li>
        <li>Where required by law, regulation, or a valid legal process.</li>
      </ul>

      <h2>6. How we protect your information</h2>
      <p>
        Uploaded documents are stored with category- and visibility-based access controls and
        served through signed, time-limited links rather than public URLs. Access to case files
        and personal data is restricted to staff who need it to serve your account. Account
        sign-in uses phone-number OTP or Google sign-in rather than a password stored on our
        servers.
      </p>

      <h2>7. How long we keep your information</h2>
      <ul>
        <li>Active case and property data is retained for as long as your case remains open.</li>
        <li>
          Closed case files, documents, and payment records are retained for a period after
          closure to meet legal, tax, and audit obligations, and to defend against or resolve
          any dispute relating to the service provided.
        </li>
        <li>
          Account profile information is retained until you ask us to delete it — see our{' '}
          <Link to="/delete-account">Delete Account</Link> page for how that works and what
          exceptions apply.
        </li>
      </ul>

      <h2>8. Your rights and choices</h2>
      <ul>
        <li>You can review and update your profile information from within the app.</li>
        <li>You can ask us what personal data we hold about you.</li>
        <li>You can ask us to correct inaccurate information.</li>
        <li>
          You can request deletion of your account and personal data — see{' '}
          <Link to="/delete-account">how to delete your account</Link>.
        </li>
        <li>You can withdraw location permission at any time from your device settings.</li>
      </ul>

      <h2>9. International use</h2>
      <p>
        Many of our clients live outside India while their property is located in the Kashmir
        Valley. Using our services from another country means your information may be accessed
        by our team and service providers in India in order to deliver the service. We take
        reasonable steps to keep your information secure regardless of where it's accessed from.
      </p>

      <h2>10. Cookies and tracking</h2>
      <p>
        This website does not currently use advertising or third-party tracking cookies. If
        that changes — for example, to add analytics that help us understand which pages are
        useful — we will update this section first.
      </p>

      <h2>11. Children's privacy</h2>
      <p>
        Our services are intended for adults capable of entering into property and legal
        transactions. We do not knowingly collect information from children.
      </p>

      <h2>12. Changes to this policy</h2>
      <p>
        We may update this policy as our services evolve. We'll update the "Last updated" date
        above whenever we make a change, and let you know in-app if a change is significant.
      </p>

      <h2>13. Contact us</h2>
      <p>
        Questions about this policy or your data? Reach us at{' '}
        <a href="mailto:info@houseker.com">info@houseker.com</a>, call{' '}
        <a href="tel:+919484000002">+91 9484000002</a>, or visit our team in Srinagar,
        Kashmir.
      </p>
    </LegalLayout>
  )
}
